// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZHI18AD-PYvZyJOfJzxR9xdOfM2zlxVQ',
    appId: '1:315566930014:web:094b231649c0814e119ccf',
    messagingSenderId: '315566930014',
    projectId: 'hotel-management-cea2f',
    authDomain: 'hotel-management-cea2f.firebaseapp.com',
    storageBucket: 'hotel-management-cea2f.firebasestorage.app',
    measurementId: 'G-M4LGY0MW1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhlURo5FvNWrH6TJuRvqgf55Mi37u6sB0',
    appId: '1:315566930014:android:63f1c28a7d84e69d119ccf',
    messagingSenderId: '315566930014',
    projectId: 'hotel-management-cea2f',
    storageBucket: 'hotel-management-cea2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcHSsFG8q8_QyTzx-a0t9M8FCz6jzCw8U',
    appId: '1:315566930014:ios:b59a8a7f251f0b8e119ccf',
    messagingSenderId: '315566930014',
    projectId: 'hotel-management-cea2f',
    storageBucket: 'hotel-management-cea2f.firebasestorage.app',
    iosBundleId: 'com.example.neoAssesment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcHSsFG8q8_QyTzx-a0t9M8FCz6jzCw8U',
    appId: '1:315566930014:ios:b59a8a7f251f0b8e119ccf',
    messagingSenderId: '315566930014',
    projectId: 'hotel-management-cea2f',
    storageBucket: 'hotel-management-cea2f.firebasestorage.app',
    iosBundleId: 'com.example.neoAssesment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZHI18AD-PYvZyJOfJzxR9xdOfM2zlxVQ',
    appId: '1:315566930014:web:89d0f3f443946a77119ccf',
    messagingSenderId: '315566930014',
    projectId: 'hotel-management-cea2f',
    authDomain: 'hotel-management-cea2f.firebaseapp.com',
    storageBucket: 'hotel-management-cea2f.firebasestorage.app',
    measurementId: 'G-0SNRVTG96H',
  );
}
